export const fetchAddress = "http://192.168.1.32:3000";
// A CHANGER AVEC URL BACKEND QUAND DEPLOYE
// ATTENTION : POUR LES BESOINS DU DEV, COMPONENT DANS GITIGNORE → À ENLEVER QUAND ON AURA DEPLOYE LE BACKEND
